"""redesign_place_schema_add_photos_reviews_options_interactions

Revision ID: 002
Revises: 001
Create Date: 2025-10-06 21:07:48.208527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('business_status', sa.String(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('payment_options', sa.JSON(), nullable=True),
    sa.Column('parking_options', sa.JSON(), nullable=True),
    sa.Column('fuel_options', sa.JSON(), nullable=True),
    sa.Column('ev_charge_options', sa.JSON(), nullable=True),
    sa.Column('price_range', sa.JSON(), nullable=True),
    sa.Column('accessibility_options', sa.JSON(), nullable=True),
    sa.Column('takeout', sa.Boolean(), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.Column('dine_in', sa.Boolean(), nullable=True),
    sa.Column('curbside_pickup', sa.Boolean(), nullable=True),
    sa.Column('reservable', sa.Boolean(), nullable=True),
    sa.Column('serves_breakfast', sa.Boolean(), nullable=True),
    sa.Column('serves_lunch', sa.Boolean(), nullable=True),
    sa.Column('serves_dinner', sa.Boolean(), nullable=True),
    sa.Column('serves_beer', sa.Boolean(), nullable=True),
    sa.Column('serves_wine', sa.Boolean(), nullable=True),
    sa.Column('serves_brunch', sa.Boolean(), nullable=True),
    sa.Column('serves_vegetarian_food', sa.Boolean(), nullable=True),
    sa.Column('serves_cocktails', sa.Boolean(), nullable=True),
    sa.Column('serves_dessert', sa.Boolean(), nullable=True),
    sa.Column('serves_coffee', sa.Boolean(), nullable=True),
    sa.Column('outdoor_seating', sa.Boolean(), nullable=True),
    sa.Column('live_music', sa.Boolean(), nullable=True),
    sa.Column('menu_for_children', sa.Boolean(), nullable=True),
    sa.Column('good_for_children', sa.Boolean(), nullable=True),
    sa.Column('allows_dogs', sa.Boolean(), nullable=True),
    sa.Column('restroom', sa.Boolean(), nullable=True),
    sa.Column('good_for_groups', sa.Boolean(), nullable=True),
    sa.Column('good_for_watching_sports', sa.Boolean(), nullable=True),
    sa.Column('pure_service_area_business', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    op.create_index(op.f('ix_place_options_id'), 'place_options', ['id'], unique=False)
    op.create_table('place_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('attributions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_photos_id'), 'place_photos', ['id'], unique=False)
    op.create_table('place_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('relative_publish_time_description', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_reviews_id'), 'place_reviews', ['id'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.Enum('LIKE', 'DISLIKE', 'SKIP', 'CHECK_IN', 'OPEN', name='interactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interactions_created_at'), 'user_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_interactions_id'), 'user_interactions', ['id'], unique=False)
    op.drop_constraint(op.f('place_categories_place_id_fkey'), 'place_categories', type_='foreignkey')
    op.create_foreign_key(None, 'place_categories', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.add_column('places', sa.Column('name', sa.String(), nullable=False))
    op.add_column('places', sa.Column('primary_category_id', sa.Integer(), nullable=True))
    op.add_column('places', sa.Column('google_maps_uri', sa.String(), nullable=True))
    op.add_column('places', sa.Column('website_uri', sa.String(), nullable=True))
    op.add_column('places', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('places', sa.Column('opening_hours', sa.JSON(), nullable=True))
    op.add_column('places', sa.Column('user_rating_count', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_places_city'), table_name='places')
    op.drop_index(op.f('ix_places_title'), table_name='places')
    op.drop_constraint(op.f('places_google_place_id_key'), 'places', type_='unique')
    op.create_index(op.f('ix_places_google_place_id'), 'places', ['google_place_id'], unique=True)
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.create_foreign_key(None, 'places', 'categories', ['primary_category_id'], ['id'])
    op.drop_column('places', 'city')
    op.drop_column('places', 'price_level')
    op.drop_column('places', 'image_url')
    op.drop_column('places', 'website')
    op.drop_column('places', 'phone')
    op.drop_column('places', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('places', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('price_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    #op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_index(op.f('ix_places_google_place_id'), table_name='places')
    op.create_unique_constraint(op.f('places_google_place_id_key'), 'places', ['google_place_id'])
    op.create_index(op.f('ix_places_title'), 'places', ['title'], unique=False)
    op.create_index(op.f('ix_places_city'), 'places', ['city'], unique=False)
    op.drop_column('places', 'user_rating_count')
    op.drop_column('places', 'opening_hours')
    op.drop_column('places', 'phone_number')
    op.drop_column('places', 'website_uri')
    op.drop_column('places', 'google_maps_uri')
    op.drop_column('places', 'primary_category_id')
    op.drop_column('places', 'name')
    op.drop_constraint('place_categories_place_id_fkey', 'place_categories', type_='foreignkey')
    op.create_foreign_key(op.f('place_categories_place_id_fkey'), 'place_categories', 'places', ['place_id'], ['id'])
    op.drop_index(op.f('ix_user_interactions_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_created_at'), table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index(op.f('ix_place_reviews_id'), table_name='place_reviews')
    op.drop_table('place_reviews')
    op.drop_index(op.f('ix_place_photos_id'), table_name='place_photos')
    op.drop_table('place_photos')
    op.drop_index(op.f('ix_place_options_id'), table_name='place_options')
    op.drop_table('place_options')

    op.execute('DROP TYPE IF EXISTS interactiontype;')
    # ### end Alembic commands ###
