"""add_check_in_photos_and_visibility

Revision ID: 003
Revises: 002
Create Date: 2025-10-06 21:48:14.550008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first
    checkinvisibility_enum = sa.Enum('PRIVATE', 'PUBLIC', 'FRIENDS', name='checkinvisibility')
    checkinvisibility_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('check_in_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_photos_id'), 'check_in_photos', ['id'], unique=False)
    op.add_column('check_ins', sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', 'FRIENDS', name='checkinvisibility'), nullable=False, server_default='PUBLIC'))
    op.drop_column('check_ins', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_ins', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('check_ins', 'visibility')
    op.drop_index(op.f('ix_check_in_photos_id'), table_name='check_in_photos')
    op.drop_table('check_in_photos')
    
    # Drop the enum type
    op.execute('DROP TYPE IF EXISTS checkinvisibility;')
    # ### end Alembic commands ###
